export interface Tariff {
  discount: number,
  extCmd: string,
  manualActivate: number,
  feesType: number,
  name: string,
  period: number,
  tpId: number,
  activateNotification: number,
  periodAlignment: number,
  nextAbonDate: string,
  userCount: number,
  description: string,
  price: number,
  priority: number,
  vat: number,
  paymentType: number,
  createAccount: number,
  userPortal: number,
}
